/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tiktaktoe;

import JDBC.DBConnection;
import javax.swing.JFrame;
import javax.swing.WindowConstants;

/**
 *
 * @author JBHIFI
 */
public class FillForm extends javax.swing.JFrame {

    /**
     * Creates new form FillForm
     */
    String mode;
    DBConnection dbcon;
    static JFrame f1;

    public FillForm(String mode) {
        initComponents();
        MainMenu.m.setVisible(false);
        this.mode = mode;
        dbcon = new DBConnection();
        if (!(this.mode.equals("TwoPlayerMode"))) {
            txtplayername2.setEnabled(false);
        }
        setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);
        this.setLocationRelativeTo(null);
        f1 = new JFrame();
        f1.setUndecorated(true);
        f1.setResizable(false);

    }

    private FillForm() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtplayername1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtplayername2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel1.setText("Player1 Name : ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 157, 58));

        txtplayername1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        txtplayername1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txtplayername1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtplayername1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtplayername1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, 171, 58));

        jButton1.setBackground(new java.awt.Color(102, 51, 0));
        jButton1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jButton1.setText("Start");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 350, 122, 51));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel2.setText("Player2 Name : ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 157, 58));

        txtplayername2.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        txtplayername2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txtplayername2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtplayername2ActionPerformed(evt);
            }
        });
        getContentPane().add(txtplayername2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 170, 171, 58));

        jButton2.setBackground(new java.awt.Color(204, 102, 0));
        jButton2.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 350, 120, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/back2.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtplayername1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtplayername1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtplayername1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String sql = "";
        if (this.mode.equals("easy")) {
            EasyMode easymode = new EasyMode(txtplayername1.getText());
            f1.setContentPane(easymode);
            f1.pack();
            f1.setTitle("Tik Tak Toe");
            if (txtplayername1.getText().equals("")) {
                sql = "INSERT INTO easymode(wins,loses,draws,name) values(0,0,0,'" + "Player1" + "')";
            } else {
                sql = "INSERT INTO easymode(wins,loses,draws,name) values(0,0,0,'" + txtplayername1.getText() + "')";
            }
            dbcon.putData(sql);
            f1.setVisible(true);

        } else if (this.mode.equals("hard")) {
            Controller con1 = new Controller(txtplayername1.getText());
            f1.setContentPane(con1);
            f1.pack();
            f1.setTitle("Tik Tak Toe");
            if (txtplayername1.getText().equals("")) {
                sql = "INSERT INTO hardmode(wins,loses,draws,name) values(0,0,0,'" + "Player1" + "')";
            } else {
                sql = "INSERT INTO hardmode(wins,loses,draws,name) values(0,0,0,'" + txtplayername1.getText() + "')";
            }
            dbcon.putData(sql);
            f1.setVisible(true);

        } else if (this.mode.equals("TwoPlayerMode")) {
            Live l1 = new Live(txtplayername1.getText(), txtplayername2.getText());
            f1.setContentPane(l1);
            f1.pack();
            f1.setTitle("Tik Tak Toe");
            if (txtplayername1.getText().equals("") && txtplayername2.getText().equals("")) {
                sql = "INSERT INTO twoplayer(player1name,player2name,player1wins,player2wins,draws) values('" + "Player1" + "','" + "Player2" + "',0,0,0)";
            } else if (txtplayername1.getText().equals("") && !txtplayername2.getText().equals("")) {
                sql = "INSERT INTO twoplayer(player1name,player2name,player1wins,player2wins,draws) values('" + "Player1" + "','" + txtplayername2.getText() + "',0,0,0)";
            } else if (!txtplayername1.getText().equals("") && txtplayername2.getText().equals("")) {
                sql = "INSERT INTO twoplayer(player1name,player2name,player1wins,player2wins,draws) values('" + txtplayername1.getText() + "','" + "Player2" + "',0,0,0)";
            } else {
                sql = "INSERT INTO twoplayer(player1name,player2name,player1wins,player2wins,draws) values('" + txtplayername1.getText() + "','" + txtplayername2.getText() + "',0,0,0)";
            }
            dbcon.putData(sql);
            f1.setVisible(true);
        }
        MainMenu.frm1.setVisible(false);
        f1.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtplayername2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtplayername2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtplayername2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
        MainMenu.m.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    void updateDatabase(String player) {

        int wins = 0;
        int loses = 0;
        int draws = 0;
        String sql = "INSERT INTO singleplayer(wins,loses,draws,name) values(0,0,0,'" + player + "')";
        dbcon.putData(sql);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FillForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FillForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FillForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FillForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FillForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtplayername1;
    private javax.swing.JTextField txtplayername2;
    // End of variables declaration//GEN-END:variables
}
